### ISSUE TITLE
build created not being populated correctly

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#144]
## Description

🐛  VELA_BUILD_CREATED is returning 0 unless the build is restarted.

## Useful Information

reproduced with the following step
```yaml
version: "1"
steps:
  - name: test
    image: golang
    commands:
      - echo "$VELA_BUILD_CREATED"
```
then restart it

**Comment by davidvader** [comment]
Created is not set here
https://github.com/go-vela/server/blob/master/api/webhook.go#L125
and is never updated

restarting build works because of this line
https://github.com/go-vela/server/blob/master/api/build.go#L578

**Comment by kennyli92** [comment]
As per our conversation here https://target-tts.slack.com/archives/CN8N93Q6L/p1603988454434200 , I'd like to include `VELA_BUILD_ENQUEUED`, `VELA_BUILD_FINISHED`, and `VELA_BUILD_STARTED` as part of this issue. If possible, could we add an env var to get the current time? Ultimately, I want to be able to calculate the build time and queue time from these variables. Thanks!

**Comment by kennyli92** [comment]
As per our conversation, I'd like to include VELA_BUILD_ENQUEUED, VELA_BUILD_FINISHED, and VELA_BUILD_STARTED as part of this issue -- they're all returning 0. If possible, could we add an env var to get the current time? Ultimately, I want to be able to calculate the build time and queue time from these variables. Thanks!

**Comment by podollb** [comment]
is this still an issue?

**Comment by kennyli92** [comment]
Partially...I'm getting timestamp for `VELA_BUILD_CREATED` and `VELA_BUILD_STARTED`. `VELA_BUILD_ENQUEUED` and `VELA_BUILD_FINISHED` are still returning `0`

**Comment by kennyli92** [comment]
Partially...I'm getting timestamp for `VELA_BUILD_CREATED` and `VELA_BUILD_STARTED`. `VELA_BUILD_ENQUEUED` and `VELA_BUILD_FINISHED` are still returning `0`

**Comment by kneal** [comment]
We will be removing the `*_FINISHED` variable is:

* it's not accurate to any behavior and 
*  it's not possible to inject a finished time because when you get that time the step or build should no longer be executing. 

So, there's nothing to inject that timestamp into other than ensuring the build record in the database is accurate to that time. We are looking to more accurately present what's going on in the system and remove any false advertising of what the variable is actually doing.

**Comment by kneal** [comment]
I have been able to validate that `VELA_BUILD_CREATED` is now getting populated for all steps and stages correctly. 

A few notes I would like to add around the [substitution](https://github.com/drone/envsubst) library we import. 

Escaping with the library is **very** particular. When creating complex substitutions like:

```yaml
  - name: echo
    image: alpine:latest
    commands:
      - 'echo "Build tag: $VELA_BUILD_CREATED.0.${VELA_BUILD_NUMBER}-z${VELA_BUILD_COMMIT:0:7}"'
```

The smallest amount of escaping is very important and that's because the string `echo ...` is evaluated a rune at a time. So, providing a properly escaped string is a **must**.
