### ISSUE TITLE
API : GET builds by amount or time window 

### ISSUE THREAD

**Issue by gelicia** [go-vela/community#187]
## Description

In the API for getting a list of builds (https://go-vela.github.io/docs/reference/api/build/get/#parameters), being able to set a parameter to return either a set number of results or an indefinite amount of results within a certain time period (within a server defined limit of results)

## Value

 As of right now, it seems like you can only retrieve 10 builds at a time. Being able to pull data from further back is important for establishing a pattern on when builds started failing regularly. 

## Definition of Done

Being able to run `GET  /api/v1/repos/:org/:repo/builds?limit=x` and/or `GET  /api/v1/repos/:org/:repo/builds?startdate=y&daysWindow=z` and have it retrieve more than 10 results at a time.

## Effort  (Optional)

N/A

## Impacted Personas (Optional)

Users of the Vela server who want to injest build data from the API

**Comment by JordanSussman** [comment]
The majority of API endpoints support pagination by utilizing the query parameters of `per_page` and `page` to return more results beyond the default of 10.

- `page` - specifies the page of results to return
- `per_page` - specifies the number of results to return per page

A simple curl request to return the 2nd page with 20 results looks like - `curl -H 'Authorization: Bearer <token>' https://vela.company.com/api/v1/repos/<org>/<repo>/builds?per_page=20&page=2`.

Looks like we may need to open another issue to document pagination since the [existing issues](https://github.com/go-vela/community/issues?q=is%3Aissue+is%3Aopen+pagination) are specific to a subset of the docs.

**Comment by wass3r** [comment]
Yea, we talked offline a bit. Definitely needs to get added to documentation along with a couple of other missing parameters.

I think there is still merit in something that narrows down based on date or time, though.

**Comment by JordanSussman** [comment]
> I think there is still merit in something that narrows down based on date or time, though.

Probably worthwhile to eventually explore a `/v2` API that utilizes [GraphQL](https://graphql.org/) to allow parsing based on date or whatever other limit.
