### ISSUE TITLE
fix vela-kaniko unpacking rootfs with docker mounts

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#253]
## Description

Currently, when using the [go-vela/vela-kaniko](https://github.com/go-vela/vela-kaniko) plugin to build a Docker image on a host with volumes mounted from the host, you'll likely experiences errors like:

```
device or resource busy
```

This can occur for a number of different host mounts but the specific one we're facing is:

```
unlinkat /etc/ssl/certs/ca-certificates.crt: device or resource busy
```

This appears to be a known issue with Kaniko:

* https://github.com/GoogleContainerTools/kaniko/issues/946
* https://github.com/GoogleContainerTools/kaniko/issues/1424
* https://github.com/GoogleContainerTools/kaniko/issues/1626

## Value

Enable users to build Docker images with the Vela Kaniko plugin while mounting files from the host.

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by wass3r** [comment]
## Additional context
Initially we attempted to remediate the issue on the plugin side to avoid adding code to the `pkg-runtime` module.

Unfortunately, those attempts did not solve the issue. Below, you will find a summary of some of the approaches that were attempted.

## Alternative solutions we attempted

* played with various kaniko flags on the plugin:
    * `--single-snapshot`
    * `--snapshotMode`
    * `--use-new-run`
    * `--ignore-path` (had to build from source, since not available in latest tagged release)
* played with various docker flags as well, such as:
    * `--user root`
    * `--privileged`
* mounting `/etc/ssl/certs` directory instead of cert file directly
* adding code to the kaniko plugin directly to move the `/etc/ssl/certs/ca-certificates.crt` file
   * inspired by https://github.com/GoogleContainerTools/kaniko/issues/946#issuecomment-633725153
* mounting from local relative path instead of system path for certs

Example `docker run` command that was used in testing:
```
docker run --rm \
  -e PARAMETER_CONTEXT=/workspace/ \
  -e PARAMETER_DOCKERFILE=Dockerfile.example \
  -e PARAMETER_DRY_RUN=true \
  -e PARAMETER_REGISTRY=index.docker.io \
  -e PARAMETER_REPO=index.docker.io/target/vela-kaniko \
  -e PARAMETER_TAGS=latest \
  -e VELA_BUILD_COMMIT=123abcdefg \
  -e VELA_BUILD_EVENT=push \
  -v $(shell pwd):/workspace \
  -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates:rw \
  vela-kaniko:local
```

## Other possible alternatives to consider in the future

* contributing back the kaniko project
* fork kaniko and implement short term fix to use with intent of eventually pushing it upstream

**Comment by michael81877** [comment]
Just FYI, i was able to work around this by using `--ignore-path`. I ran into the same `unlinkat /etc/ssl/certs/ca-certificates.crt: device or resource busy` error and just added the following argument to my kaniko script:

```
--ignore-path=/etc/ssl/certs
```

Then the docker image build succeeded.
