### ISSUE TITLE
Large logs aren't immediately available

### ISSUE THREAD

**Issue by meinenec** [go-vela/community#261]
## Description

Ran into a few instances of large logs (82,000+ lines and somewhere between 12 and 19MB) aren't immediately available after the step, or build finishes. The logs appear over time, but I haven't identified how long it takes.
This doesn't seem to affect other builds happening at the same time.

## Value

Users would like to be able to view their logs and troubleshoot a failed step.

## Useful Information

We were able to replicate by downloading the step logs after the build completed then again an hour later.

1. What is the output of `vela --version`?

N/A

2. What operating system is being used?

N/A

3. Any other important details?

N/A

**Comment by wass3r** [comment]
this issue was more pronounced with byte-chunked version of logs. we recommend using `time-chunks` for the worker configuration https://go-vela.github.io/docs/administration/worker/reference/executor/#configuration (`VELA_EXECUTOR_LOG_METHOD`). as a side note, `byte-chunks` will be removed as an option in a future release.
