### ISSUE TITLE
Allow stages to fail independently

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#546]
## Description

Allow build steps to fail independently.

Currently, stages execute in parallel, which is useful for building artifacts that do not depend on other stages. However, a failure of one step causes all stages to terminate. We would like an option to allow other stages to continue if a step fails on a different stage.

For example, Drone's matrix builds are independent in this way.

## Value

We rely on this granularity to allow deployments to proceed in all healthy environments. Without this feature, our entire deployment process may be halted by an intermittent failure or an outage in a single environment. By aggressively canceling other stages, this can leave our environment in an inconsistent state.

**Comment by 42shadow42** [comment]
We are also experiencing problems with the lack of this feature when attempting to put together a mono-repo with independent build and release cycles.

**Comment by chrispdriscoll** [comment]
This feature can impact the core processing so extensive testing is needed to verify we understand any/all impacts to this change. Our v0.14 release had to be rolled back due to changes in the core so we want to be extra careful around this change. Given the scope of work already included in v0.15 and the plug-in releases, there is not enough time to include this is the upcoming release so I'm moving this to the v0.16 release.
