### ISSUE TITLE
Enable signing pipeline configurations

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#62]
## Description

Allow the ability to "sign" a Vela pipeline (`.vela.yml`) that generates some special signature. This signature is meant to be an extra layer of security that marks this pipeline as "verified" or "approved" to be executed.

That signature could be added directly to the end of the Vela pipeline, or perhaps it gets put into its own file alongside the pipeline? i.e. `.vela.signature`, `.vela.sig`, `.vela.yml.sig`.

This configuration should remain optional and configurable on if the signature is required or not. If the repo is configured to require this signature, then Vela should check the validity of the signature before creating a new build for the repo.

## Value

* improved security and access control
* remove the security risk with secrets in a `pull_request` build

## Definition of Done

Users can generate a signature for a Vela pipeline (`.vela.yml`)
Vela will validate the contents of that signature before creating a new build for a repo

## Effort  (Optional)

2 weeks

## Impacted Personas (Optional)

everyone

**Comment by GregoryDosh** [comment]
As an additional ability to limit the secrets would be for certain high risk events. Perhaps for pull_requests you can limit the secrets to only certain teams in GitHub. This could extend beyond just pull_requests, but if some secrets are available for certain groups it might eliminate the need for a signing config in most scenarios. Presumably if you're part of the repo and have write access then you should have access to all secrets regardless the event since you could easily change those settings? It would require a fair amount of documentation and signage for the end users to understand why secrets weren't available for a build.

**Comment by plyr4** [comment]
you could argue the spirit of this issue is complete through https://github.com/go-vela/server/pull/1016 and the other security overhauls.
feel free to open another issue if needed
