### ISSUE TITLE
Display owner of Vela repo

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#69]
## Description

Currently, we don't have a great way to display who "owns" the repository in Vela.

This can lead to issues when trying to troubleshoot why builds aren't being triggered for a repo if the underlying issue is in relation to who originally added the repo in Vela.

Specifically, we've seen issues where a user adds a repo to Vela, and than that user's account is disabled/deactivated on the VCS side causing builds not to trigger for Vela.

As long as there is no added security risk with exposing this information, we should consider adding some sort of way to visualize this information.

## Value

* provide extra information about a repo
* enhance ability to troubleshoot issues

## Definition of Done

A user can view the owner of a Vela repo.

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

everyone

**Comment by wass3r** [comment]
To do this, we'd have to be able to lookup a user by ID because that's the information we have on the repo object (https://github.com/go-vela/types/blob/v0.8.2/library/repo.go#L14). Currently, the user endpoint expects the name to be passed (https://github.com/go-vela/server/blob/v0.8.4/router/user.go#L35). 

I don't believe we're currently consuming this endpoint?

Any objection to opening up that endpoint (so it's not restricted to platform admins) and changing it to use ID instead of name?

**Comment by colindean** [comment]
I've developed a desire for this to audit ownership of repos in my orgs on a quest to reassign ownership to a particular user or service account.
