### ISSUE TITLE
Issue while executing vela CLI

### ISSUE THREAD

**Issue by CargillRamya** [go-vela/community#903]
I'm trying to execute vela pipeline through CLI mode. When I try running the command below issue appears

<img width="485" alt="Vela_CLI_issue" src="https://github.com/go-vela/community/assets/150126476/0dc16c43-a465-47d9-8547-526324b1fe50">

**Comment by wass3r** [comment]
couple of things:
1) the command should just be `vela exec pipeline` if you are using the default filename of `.vela.yml` in your directory. Otherwise, if you have a pipeline that is named something different than `.vela.yml` it would be `vela exec pipeline --file .different.yml` (note the `--file` vs `file` difference), for example.
2) the message seems to indicate that the CLI isn't able to use the socket for the Docker daemon. is Docker running on this machine?

**Comment by wass3r** [comment]
going to close this as there's been no follow-up. feel free to reply or open a new issue.
